### ISSUE TITLE
statsd with datadog-agent on AWS ECR / hostname problem

### ISSUE THREAD

**Issue by mycaule** [DataDog/datadogpy#291]
Hello I am getting this error when using stasd
https://datadogpy.readthedocs.io/en/latest/#datadog.statsd

```
hostname Unknown host is:open 
```

This is how I initialize datadog in my code.

```python
from datadog import initialize, statsd
initialize(statsd_host='localhost', statsd_port=8125)
statsd.increment('home.page.hits')
```

Is this a bug ? How can I diagnosis the problem ?
https://docs.datadoghq.com/agent/faq/how-datadog-agent-determines-the-hostname/

I am also trying to use datadog-agent on AWS ECR (cluster of Dockers) there.

Thank you.

**Comment by smallcrew** [comment]
The hostname warning is probably not related to the statsd issue

Manage to makes this work on ECS using the following properties in the cfn ContainerDefinitions configuration:
```yaml
PortMappings:
  - ContainerPort: 8125
    HostPort: 8125
    Protocol: udp
  Environment:
    - Name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
      Value: true
```
